#!/usr/bin/env python3
"""Universal case ledger clerk.

Scans every jurisdiction-local citator/caselaw across the realm and assembles ONE master index of all
LEXBY rulings, keyed on the single neutral-citation series (CASE-LAW s. 11(d), s. 19(5), s. 22). This is
the one place that sees every case. Token-light; runnable by cron or a Haiku clerk.

Usage:  python3 build-ledger.py            (writes ministry-of-justice/ledger/INDEX.md)
"""
import re, pathlib, datetime, sys

REALM = pathlib.Path(__file__).resolve().parents[2]            # ~/agent-universe
LEDGER = REALM / "ministry-of-justice" / "ledger" / "INDEX.md"

# Neutral-citation forms (provenance scheme): [YEAR] REALM-SC/PC/CA n, [YEAR] <DIVISION> n
# (ENG/CHAN), [YEAR] CC-<repo> n. The realm/harvey/acmeco reconstitution is complete, so the
# retired LEXBY-* series is no longer counted as live rulings (it survives only as provenance
# notes inside reconstituted files; counting it would phantom-double rulings).
CITE = re.compile(
    r"\[(20\d\d)\]\s+(?:REALM-(?:SC|PC|CA)|ENG|CHAN|CC-[A-Z0-9-]+)\s+\d+",
    re.I)

SKIP_DIRS = {".git", "node_modules", ".justice/pdfs", "renderer"}

def jurisdiction_of(path: pathlib.Path) -> str:
    """Best-effort: name the jurisdiction-repo a ruling file belongs to (for signposting)."""
    rel = path.relative_to(REALM).parts
    if "legal-department" in rel:
        i = rel.index("legal-department")
        return "Legal Division / " + (rel[i+1] if len(rel) > i+1 else "")
    if "engineering-department" in rel:
        return "Engineering Division"
    if rel and rel[0] in ("caselaw", "community", ".justice"):
        return "Ministry of Justice (apex)"
    return "/".join(rel[:-1])

rows = {}   # citation -> (jurisdiction, source-path, context-line)
for f in REALM.rglob("*.md"):
    parts = set(f.relative_to(REALM).parts)
    if parts & {".git", "node_modules"}:
        continue
    # only scan caselaw / citator / judgment files
    low = str(f).lower()
    if not any(k in low for k in ("caselaw", "citator", "/.justice/", "index.md", "judgment", "lexby")):
        continue
    try:
        text = f.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        continue
    for m in CITE.finditer(text):
        cite = re.sub(r"\s+", " ", m.group(0)).strip()
        if cite in rows:
            continue
        # grab a short context (the line, trimmed)
        line = text[text.rfind("\n", 0, m.start())+1 : text.find("\n", m.end())].strip()
        line = re.sub(r"\s+", " ", line)[:160]
        rows[cite] = (jurisdiction_of(f), str(f.relative_to(REALM)), line)

def sort_key(c):
    tier = ("SC" in c, "CA" in c, "INC" in c, "FI" in c)  # apex first
    num = int(re.search(r"(\d+)\s*$", c).group(1))
    return (not tier[0], not tier[1], not tier[2], not tier[3], num, c)

out = [f"# Universal Case Ledger\n",
       f"The realm's master index of every LEXBY ruling, one series, one citator (CASE-LAW s. 11(d) / s. 22).",
       f"Generated by the clerk ({len(rows)} rulings). Re-run `build-ledger.py` after any new ruling.\n",
       "| Citation | Jurisdiction | Source | Matter / context |",
       "|---|---|---|---|"]
for c in sorted(rows, key=sort_key):
    j, src, ctx = rows[c]
    ctx = ctx.replace("|", "\\|")
    out.append(f"| {c} | {j} | `{src}` | {ctx} |")
LEDGER.write_text("\n".join(out) + "\n")
print(f"ledger: {len(rows)} rulings -> {LEDGER.relative_to(REALM)}")
